### ISSUE TITLE
Error loading vgg weights

### ISSUE THREAD

**Issue by Recoil77** [explainingai-code/StableDiffusion-PyTorch#23]
Hello. Did all as described in manual.
Python 3.8
pip install -r requirements.txt   all fine
loadaded vgg.pth
prepared  mnist dataset.

but while training  VQVAE. got this error

Found 60000 images for split train
Loading model from: /root/code/StableDiffusion-PyTorch/models/weights/v0.1/vgg.pth
Traceback (most recent call last):
  File "/root/code/StableDiffusion-PyTorch/.conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/code/StableDiffusion-PyTorch/.conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/code/StableDiffusion-PyTorch/tools/train_vqvae.py", line 204, in <module>
    train(args)
  File "/root/code/StableDiffusion-PyTorch/tools/train_vqvae.py", line 73, in train
    lpips_model = LPIPS().eval().to(device)
  File "/root/code/StableDiffusion-PyTorch/models/lpips.py", line 94, in __init__
    self.load_state_dict(torch.load(model_path, map_location=device), strict=False)
  File "/root/code/StableDiffusion-PyTorch/.conda/lib/python3.8/site-packages/torch/serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/root/code/StableDiffusion-PyTorch/.conda/lib/python3.8/site-packages/torch/serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x0a'.

Please help.

**Comment by soulslicer** [comment]
Yes it is broken

**Comment by explainingai-code** [comment]
Thank you @soulslicer (have now updated the readme to indicate the same)
@Recoil77 So sorry for completely missing to respond on this. I know its been long but were you able to get the it working ?
